/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.shikha.stackoverflow.model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TagRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6480860145224826160L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TagRecord\",\"namespace\":\"com.shikha.stackoverflow.model\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"numeric ID of tag\",\"default\":\"\"},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"tag name\",\"default\":\"\"},{\"name\":\"count\",\"type\":\"long\",\"doc\":\"count of tag\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** numeric ID of tag */
  @Deprecated public java.lang.CharSequence id;
  /** tag name */
  @Deprecated public java.lang.CharSequence name;
  /** count of tag */
  @Deprecated public long count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TagRecord() {}

  /**
   * All-args constructor.
   * @param id numeric ID of tag
   * @param name tag name
   * @param count count of tag
   */
  public TagRecord(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.Long count) {
    this.id = id;
    this.name = name;
    this.count = count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: count = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return numeric ID of tag
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * numeric ID of tag
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return tag name
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * tag name
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'count' field.
   * @return count of tag
   */
  public java.lang.Long getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * count of tag
   * @param value the value to set.
   */
  public void setCount(java.lang.Long value) {
    this.count = value;
  }

  /**
   * Creates a new TagRecord RecordBuilder.
   * @return A new TagRecord RecordBuilder
   */
  public static com.shikha.stackoverflow.model.TagRecord.Builder newBuilder() {
    return new com.shikha.stackoverflow.model.TagRecord.Builder();
  }

  /**
   * Creates a new TagRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TagRecord RecordBuilder
   */
  public static com.shikha.stackoverflow.model.TagRecord.Builder newBuilder(com.shikha.stackoverflow.model.TagRecord.Builder other) {
    return new com.shikha.stackoverflow.model.TagRecord.Builder(other);
  }

  /**
   * Creates a new TagRecord RecordBuilder by copying an existing TagRecord instance.
   * @param other The existing instance to copy.
   * @return A new TagRecord RecordBuilder
   */
  public static com.shikha.stackoverflow.model.TagRecord.Builder newBuilder(com.shikha.stackoverflow.model.TagRecord other) {
    return new com.shikha.stackoverflow.model.TagRecord.Builder(other);
  }

  /**
   * RecordBuilder for TagRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TagRecord>
    implements org.apache.avro.data.RecordBuilder<TagRecord> {

    /** numeric ID of tag */
    private java.lang.CharSequence id;
    /** tag name */
    private java.lang.CharSequence name;
    /** count of tag */
    private long count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.shikha.stackoverflow.model.TagRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TagRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.shikha.stackoverflow.model.TagRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * numeric ID of tag
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * numeric ID of tag
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * numeric ID of tag
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * numeric ID of tag
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * tag name
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * tag name
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * tag name
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * tag name
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'count' field.
      * count of tag
      * @return The value.
      */
    public java.lang.Long getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * count of tag
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder setCount(long value) {
      validate(fields()[2], value);
      this.count = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * count of tag
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'count' field.
      * count of tag
      * @return This builder.
      */
    public com.shikha.stackoverflow.model.TagRecord.Builder clearCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public TagRecord build() {
      try {
        TagRecord record = new TagRecord();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.count = fieldSetFlags()[2] ? this.count : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
